services:
  app:
    image: ghcr.io/muhmmdfrd/digimontir:1.0.0
    container_name: digimontir-app
    restart: unless-stopped
    ports:
      - "4100:80"
    env_file:
      - .env.production
    networks:
      - digimontir-network

networks:
  digimontir-network:
    driver: bridge
